language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn run test
  - yarn run lint
deploy:
  provider: npm
  email: joel@oblador.se
  api_key:
    secure: 'E/JmYEY98KbLaw2Dmw6JFNQUtdKN8RfScuY3wjhVoKmXQ1we1hu0fCEuGtZQvYA/6rQRfcTEmvSf1w2uCOk6eYQfzKZDZ5tzQvpv7BwNMsY8D5ACphohlfB+DKx9RKM2zBrD9zaDip2SbSrB5KfYsg2R1YMq5z9ZNQrYp6kdyXNY8kyZaZtDuk18s1ZB3HTviQVQwyHPnevEEHCZZDckPfgPb4d4m32SfCqLLMkETWJojBcfQQafXoVAmK5Fhoe6WxDa6UHj6z9NqOKenKHa+u1XfZhmkMHi25x8tfmQtgFMmegQL1X0phy26zC3pLasGIsgs1lcZ/Jila5QXZIe3eoOj9w/oBJo0JQwDrKlp0o2A1x+RwhE7TxbYV04cEa6n3tY20ZBej1etFptjMtcIajqH3PRpDZ71YYl3JxgEyX3xqzL7HTOONehKLVXBuecISKxMSdr9bmQa16fYT2vXWFq8d2rkUb24Sxn/S7b60x1f2vt/6KY7d/BD6iQj4sxCJM6NWtnC3bET3Md8WbjUA7lrWxA/yXY9pAYxg0ice30w+JH4OSdbo7a9slKSPCPCNa1BUwY6R3+D74qymqu7hq/i513mxCqhWSS7LyfpTbGSXkpnSvg7UqqzqnudBlpFQcgP57oKnaf3QqPHBvRjEttAEFZjRbsZEd01k84cCk='
  on:
    tags: true
    repo: oblador/react-native-keychain
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+.*$"
