package com.oblador.keychain.utils;

public interface AppConstants {

  String DIALOG_FRAGMENT_TAG = "authFragment";

  // error codes
  String KM_ERROR_KEY_USER_NOT_AUTHENTICATED = "KM_ERROR_KEY_USER_NOT_AUTHENTICATED";
  String FINGERPRINT_AUTHENTICATION_HELP = "FINGERPRINT_AUTHENTICATION_HELP";
  String E_AUTHENTICATION_NOT_RECOGNIZED = "E_AUTHENTICATION_NOT_RECOGNIZED";
  String E_AUTHENTICATION_CANCELLED = "E_AUTHENTICATION_CANCELLED";
  String E_BIOMETRIC_NOT_SUPPORTED = "E_BIOMETRIC_NOT_SUPPORTED";
  String E_INIT_FAILURE = "E_INIT_FAILURE";
  String E_BIOMETRICS_INVALIDATED = "E_BIOMETRICS_INVALIDATED";
}