name: Lint and types

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint files
        run: yarn lint
  typescript:
    name: Typescript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check types
        run: yarn typecheck
