name: Tests

on:
  - push
  - pull_request

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent
      - name: Lint files
        run: yarn lint
  flow:
    name: Flow types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent
      - name: Check flow types
        run: yarn flow
  android:
    name: Android Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Use JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Use Android SDK
        uses: android-actions/setup-android@v2
      - name: Install example project dependencies
        run: yarn --frozen-lockfile --non-interactive --silent
        working-directory: KeychainExample
      - name: Run Android unit tests
        run: ./gradlew test
